flower_delivery/urls.py
# flower_delivery/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('fileviewer/', include('fileviewer.urls')),
    path('users/', include('users.urls')),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('orders.urls')),  # Маршруты для приложения orders
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('manage_products/', views.manage_products, name='manage_products'),
    path('add_product/', views.add_product, name='add_product'),
    path('edit_product/<int:product_id>/', views.edit_product, name='edit_product'),
    path('delete_product/<int:product_id>/', views.delete_product, name='delete_product'),
    path('add_category/', views.add_category, name='add_category'),
    path('edit_category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('delete_category/<int:category_id>/', views.delete_category, name='delete_category'),
    path('product/<int:pk>/', views.product_detail, name='product_detail'),
    path('order/create/<int:product_id>/', views.order_create, name='order_create'),
    path('order/<int:pk>/', views.order_detail, name='order_detail'),
    path('review/add/<int:product_id>/', views.add_review, name='add_review'),
    path('categories/', views.categories, name='categories'),
    path('', views.index, name='index'),
    path('api/products/', views.load_more_products, name='load_more_products'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/add/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('checkout/', views.checkout, name='checkout'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('cart/', views.cart_detail, name='cart_detail'),
    path('cart/update/<int:product_id>/', views.update_cart_item, name='update_cart_item'),
    path('orders/', views.order_list, name='order_list'),
    path('orders/cancel/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('repeat_order/<int:order_id>/', views.repeat_order, name='repeat_order'),
    path('manage_orders/', views.manage_orders, name='manage_orders'),
    path('edit_order_status/<int:order_id>/', views.edit_order_status, name='edit_order_status'),
    path('test-stars/', views.test_stars, name='test_stars'),
]

users/urls.py
# users/urls.py

from django.urls import path
from . import views

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('profile/', views.profile, name='profile'),
    path('set_default_address/', views.set_default_address, name='set_default_address'),
    path('add_address/', views.add_address, name='add_address'),
    path('add_address_page/', views.add_address_page, name='add_address_page'),
    path('search_address/', views.search_address, name='search_address'),
    path('delete_address/<int:address_id>/', views.delete_address, name='delete_address'),
    path('delete_selected_addresses/', views.delete_selected_addresses, name='delete_selected_addresses'),
]

orders/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from .bot_utils import notify_order_cancellation
from django.db.models import Avg

class Cart(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    session_key = models.CharField(max_length=40, blank=True, null=True)

    def __str__(self):
        return f"Корзина {self.user.username if self.user else self.session_key}"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

class ProductCategory(models.Model):
    name = models.CharField(_("Название категории"), max_length=100)
    description = models.TextField(_("Описание"), blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Категория продукта")
        verbose_name_plural = _("Категории продуктов")

class Product(models.Model):
    name = models.CharField(_("Название"), max_length=100)
    price = models.DecimalField(_("Цена"), max_digits=10, decimal_places=2)
    image = models.ImageField(_("Изображение"), upload_to='products/')
    category = models.ForeignKey(ProductCategory, verbose_name=_("Категория"), on_delete=models.CASCADE, related_name='products')
    description = models.TextField(_("Описание"), blank=True, null=True)

    def __str__(self):
        return self.name

    @property
    def avg_rating(self):
        return self.reviews.aggregate(Avg('rating'))['rating__avg'] or 0

    class Meta:
        verbose_name = _("Продукт")
        verbose_name_plural = _("Продукты")

class Order(models.Model):
    STATUS_CHOICES = [
        ('P', 'В ожидании'),
        ('C', 'Завершен'),
        ('F', 'Неудачно'),
        ('X', 'Отменен'),
    ]

    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Пользователь"), on_delete=models.CASCADE)
    products = models.ManyToManyField('Product', verbose_name=_("Продукты"), through='OrderProduct')
    status = models.CharField(_("Статус"), max_length=1, choices=STATUS_CHOICES, default='P')
    created_at = models.DateTimeField(_("Дата создания"), auto_now_add=True)
    delivery_address = models.ForeignKey('users.Address', verbose_name=_("Адрес доставки"), on_delete=models.SET_NULL, null=True, blank=True)


    def cancel(self):
        if self.status == 'P':
            self.status = 'X'
            self.save()
            notify_order_cancellation(self)

    def __str__(self):
        return f"Заказ {self.id} от {self.user.username}"

    class Meta:
        verbose_name = _("Заказ")
        verbose_name_plural = _("Заказы")

class OrderProduct(models.Model):
    order = models.ForeignKey(Order, verbose_name=_("Заказ"), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name=_("Продукт"), on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(_("Количество"))

    def __str__(self):
        return f"{self.quantity} x {self.product.name}"

    class Meta:
        verbose_name = _("Продукт заказа")
        verbose_name_plural = _("Продукты заказа")

class Review(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, verbose_name=_("Пользователь"), on_delete=models.CASCADE)
    product = models.ForeignKey(Product, verbose_name=_("Продукт"), on_delete=models.CASCADE, related_name='reviews')
    rating = models.PositiveIntegerField(_("Рейтинг"))
    comment = models.TextField(_("Комментарий"))
    created_at = models.DateTimeField(_("Дата создания"), auto_now_add=True)

    def __str__(self):
        return f"Отзыв {self.id} от {self.user.username}"

    class Meta:
        verbose_name = _("Отзыв")
        verbose_name_plural = _("Отзывы")


class Report(models.Model):
    date = models.DateField(_("Дата"))
    total_sales = models.DecimalField(_("Общие продажи"), max_digits=10, decimal_places=2)
    total_orders = models.PositiveIntegerField(_("Общее количество заказов"))

    def __str__(self):
        return f"Отчет за {self.date}"

    class Meta:
        verbose_name = _("Отчет")
        verbose_name_plural = _("Отчеты")

orders/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Product, ProductCategory, Cart, CartItem, Order, OrderProduct, Review
from .forms import ProductForm, ProductCategoryForm, OrderForm, ReviewForm
from django.contrib.auth.decorators import login_required, user_passes_test
from django.urls import reverse
from django.core.paginator import Paginator
from django.http import JsonResponse
from .bot_utils import notify_new_order
from django.contrib import messages
from users.models import Address

import logging

logger = logging.getLogger('my_custom_logger')

def get_cart(request):
    if request.user.is_authenticated:
        logger.debug(f"Authenticated user: {request.user}")
        cart, created = Cart.objects.get_or_create(user=request.user)
        logger.debug(f"User cart found or created: {cart.id} ")

        session_key = request.session.session_key
        if session_key:
            logger.debug(f"Session key: {session_key}")
            try:
                guest_cart = Cart.objects.get(session_key=session_key)
                logger.debug(f"Guest cart found: {guest_cart.id}")

                if guest_cart and guest_cart.items.exists():
                    for item in guest_cart.items.all():
                        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=item.product)
                        if not created:
                            cart_item.quantity += item.quantity
                            cart_item.save()
                        logger.debug(f"Added item {item.product.name} (Quantity: {item.quantity}) to user cart")

                    guest_cart.delete()
                    logger.debug("Guest cart deleted after merging")
            except Cart.DoesNotExist:
                logger.debug("No guest cart found for this session")
    else:
        session_key = request.session.session_key
        if not session_key:
            request.session.create()
            session_key = request.session.session_key
            logger.debug(f"New session created with key: {session_key}")
        cart, created = Cart.objects.get_or_create(session_key=session_key)
        logger.debug(f"Guest cart found or created: {cart.id} (Created: {created})")

    return cart

def add_to_cart(request, product_id):
    product = get_object_or_404(Product, id=product_id)

    if request.user.is_authenticated:
        cart, created = Cart.objects.get_or_create(user=request.user)
    else:
        session_key = request.session.session_key or request.session.create()
        cart, created = Cart.objects.get_or_create(session_key=session_key)

    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
    if created:
        cart_item.quantity = 1
    else:
        cart_item.quantity += 1
    cart_item.save()

    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse({'success': True})

    messages.success(request, 'Товар добавлен в корзину.')
    return redirect('cart_detail')

def cart_detail(request):
    cart = get_cart(request)
    cart_items = cart.items.all()
    total = sum(item.quantity * item.product.price for item in cart_items)
    return render(request, 'orders/cart_detail.html', {'cart_items': cart_items, 'total': total})

def remove_from_cart(request, product_id):
    cart = get_cart(request)
    cart_item = get_object_or_404(CartItem, cart=cart, product_id=product_id)
    cart_item.delete()
    return redirect('cart_detail')

@login_required
def checkout(request):
    cart = get_cart(request)
    cart_items = cart.items.all()

    if request.method == 'POST':
        if not request.user.is_authenticated:
            logger.debug("User not authenticated, saving cart items in session")
            request.session['cart_items'] = [{'product_id': item.product.id, 'quantity': item.quantity} for item in cart_items]
            logger.debug(f"Cart items saved in session: {request.session['cart_items']}")
            messages.info(request, 'Для оформления заказа необходимо авторизоваться.')
            return redirect(f'{reverse("login")}?next={reverse("checkout")}')

        if 'cart_items' in request.session:
            logger.debug(f"Restoring cart items from session: {request.session['cart_items']}")
            for item in request.session['cart_items']:
                product = get_object_or_404(Product, id=item['product_id'])
                cart_item, created = CartItem.objects.get_or_create(cart=cart, product=product)
                cart_item.quantity = item['quantity']
                cart_item.save()
                logger.debug(f"Restored item {product.name} to cart with quantity {cart_item.quantity}")
            del request.session['cart_items']

        delivery_address_id = request.POST.get('delivery_address')
        if not delivery_address_id:
            messages.error(request, "Пожалуйста, выберите адрес доставки.")
            return redirect('cart_detail')

        delivery_address = get_object_or_404(Address, id=delivery_address_id, user=request.user)

        order = Order.objects.create(user=request.user, delivery_address=delivery_address)
        logger.debug(f"Order created: {order.id}")
        for item in cart.items.all():
            OrderProduct.objects.create(order=order, product=item.product, quantity=item.quantity)
            logger.debug(f"Order item created: {item.product.name}, Quantity: {item.quantity}")
        cart.items.all().delete()
        logger.debug("Cart cleared after order creation")
        notify_new_order(order)
        return redirect('order_detail', pk=order.pk)

    addresses = request.user.addresses.all() if request.user.is_authenticated else []
    if not addresses.exists():
        messages.warning(request, "У вас нет доступных адресов доставки, чтобы оформить заказ, пожалуйста, добавьте адрес.")
        return redirect('add_address_page')

    return render(request, 'orders/checkout.html', {
        'cart_items': cart_items,
        'total': sum(item.quantity * item.product.price for item in cart_items),
        'addresses': addresses
    })

def repeat_order(request, order_id):
    original_order = get_object_or_404(Order, id=order_id, user=request.user)
    cart, created = Cart.objects.get_or_create(user=request.user)

    for item in original_order.orderproduct_set.all():
        cart_item, created = CartItem.objects.get_or_create(cart=cart, product=item.product)
        if not created:
            cart_item.quantity += item.quantity
        else:
            cart_item.quantity = item.quantity
        cart_item.save()

    return redirect('cart_detail')

@login_required
def order_detail(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order_products = OrderProduct.objects.filter(order=order)
    total = sum(item.product.price * item.quantity for item in order_products)
    return render(request, 'orders/order_detail.html', {
        'order': order,
        'order_products': order_products,
        'total': total,
    })

def index(request):
    products = Product.objects.all()

    if request.user.is_authenticated:
        carts = Cart.objects.filter(user=request.user)
        session_key = None
    else:
        session_key = request.session.session_key
        if not session_key:
            request.session.create()
            session_key = request.session.session_key

        carts = Cart.objects.filter(session_key=session_key)

    if carts.exists():
        cart = carts.first()
        if carts.count() > 1:
            for extra_cart in carts[1:]:
                for item in extra_cart.items.all():
                    cart_item, created = CartItem.objects.get_or_create(cart=cart, product=item.product)
                    if not created:
                        cart_item.quantity += item.quantity
                    cart_item.save()
                extra_cart.delete()
    else:
        cart = Cart.objects.create(
            user=request.user if request.user.is_authenticated else None,
            session_key=session_key
        )

    cart_product_ids = cart.items.values_list('product_id', flat=True)

    return render(request, 'orders/index.html', {
        'products': products,
        'cart_product_ids': cart_product_ids,
    })

def load_more_products(request):
    page = request.GET.get('page', 1)
    paginator = Paginator(Product.objects.all(), 20)
    products = paginator.get_page(page)

    products_list = [{
        'id': product.id,
        'name': product.name,
        'price': product.price,
        'image': product.image.url,
        'url': reverse('product_detail', args=[product.pk])
    } for product in products]

    return JsonResponse({'products': products_list, 'has_next': products.has_next()})

def is_manager(user):
    return user.role == 'Manager' or user.role == 'Admin'

@login_required
@user_passes_test(is_manager)
def manage_products(request):
    products = Product.objects.all()
    categories = ProductCategory.objects.all()
    return render(request, 'orders/manage_products.html', {'products': products, 'categories': categories})

@login_required
@user_passes_test(is_manager)
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('manage_products')
    else:
        form = ProductForm()
    return render(request, 'orders/add_product.html', {'form': form})

@login_required
@user_passes_test(is_manager)
def edit_product(request, product_id):
    product = get_object_or_404(Product, id=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES, instance=product)
        if form.is_valid():
            form.save()
            return redirect('manage_products')
    else:
        form = ProductForm(instance=product)
    return render(request, 'orders/edit_product.html', {'form': form})

@login_required

templates/orders/add_category.html
{% extends 'base.html' %}

{% block content %}
  <h2>Добавить категорию</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

templates/orders/add_product.html
{% extends 'base.html' %}

{% block content %}
  <h2>Добавить товар</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

templates/orders/cart_detail.html
{% extends 'base.html' %}
{% load orders_filters %}

{% block title %}Корзина{% endblock %}

{% block content %}
<h2>Корзина</h2>

{% if cart_items %}

    <div class="order-items-container">
        {% for item in cart_items %}
        <div class="order-item-card">
            <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="product-image">
            <div class="order-item-details">
                <h3 class="order-item-name">{{ item.product.name }}</h3>
                <form method="post" action="{% url 'update_cart_item' item.product.id %}" class="quantity-form">
                    {% csrf_token %}
                    <div class="quantity-controls">
                        <button type="button" class="quantity-button decrease" data-action="decrease">-</button>
                        <input type="text" name="quantity" value="{{ item.quantity }}" readonly class="quantity-input">
                        <button type="button" class="quantity-button increase" data-action="increase">+</button>
                    </div>
                </form>
                <p class="order-item-price">Цена за единицу: {{ item.product.price }} руб.</p>
                <p class="order-item-sum">Сумма: {{ item.quantity|multiply:item.product.price }} руб.</p>
                <form method="post" action="{% url 'remove_from_cart' item.product.id %}">
                    {% csrf_token %}
                    <button type="submit" class="cancel-button">Удалить</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>

    <p class="order-total">Итого: {{ total }} руб.</p>
    <div class="order-buttons">
        <form action="{% url 'index' %}" method="get" class="order-button-form">
            <button type="submit" class="continue-shopping-button">Продолжить покупки</button>
        </form>
        {% if user.addresses.exists %}
            <a href="{% url 'checkout' %}" class="confirm-button">Оформить заказ</a>
        {% else %}
            <p class="warning-message">У вас нет доступных адресов доставки. Для оформления заказа пожалуйста, <a href="{% url 'add_address_page' %}">добавите адрес доставки.</a>.</p>
        {% endif %}
    </div>

{% else %}
    <p class="empty-cart-message">Вы еще не положили товар в корзину.</p>
    <div class="order-buttons">
        <form action="{% url 'index' %}" method="get" class="order-button-form">
            <button type="submit" class="continue-shopping-button">Продолжить покупки</button>
        </form>
    </div>

{% endif %}

<script>
document.querySelectorAll('.quantity-button').forEach(button => {
    button.addEventListener('click', function(event) {
        event.preventDefault();
        const form = this.closest('form');
        const action = this.getAttribute('data-action');
        const input = form.querySelector('.quantity-input');
        let currentValue = parseInt(input.value);

        if (action === 'increase') {
            currentValue += 1;
        } else if (action === 'decrease' && currentValue > 1) {
            currentValue -= 1;
        }

        input.value = currentValue;

        // Создание и отправка POST-запроса с обновленным значением
        const formData = new FormData(form);
        formData.set('quantity', currentValue);
        formData.set('action', action);

        fetch(form.action, {
            method: 'POST',
            body: formData,
            headers: {
                'X-Requested-With': 'XMLHttpRequest',
            },
        }).then(response => {
            if (response.ok) {
                location.reload(); // Перезагрузка страницы для отображения обновлений
            }
        });
    });
});
</script>

{% endblock %}

templates/orders/categories.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Категории{% endblock %}

{% block content %}
<div id="categories-page">
    <h2 class="page-title">Категории</h2>
    {% for category in categories %}
        {% if category.products.all %}
            <h3 class="category-title">{{ category.name }}</h3>
            <div class="product-slider-container">
                <button class="scroll-button left" onclick="window.scrollLeft('{{ category.id }}')">
                    <img src="{% static 'icons/left-arrow.svg' %}" alt="Scroll Left" class="icon">
                </button>
                <div class="product-grid" id="category-{{ category.id }}">
                    {% for product in category.products.all %}
                        <div class="product-item" id="product-{{ product.id }}">
                            <a href="{% url 'product_detail' pk=product.pk %}">
                                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
                                <h4 class="product-name">{{ product.name }}</h4>
                                <p class="product-price">{{ product.price }} руб.</p>
                            </a>
                            
                            {% if product.id in cart_product_ids %}
                                <p id="in-cart-{{ product.id }}">Этот товар уже в корзине</p>
                            {% else %}
                                <button class="add-to-cart-button" data-product-id="{{ product.id }}">В корзину</button>
                            {% endif %}
                        </div>
                    {% endfor %}
                </div>
                <button class="scroll-button right" onclick="window.scrollRight('{{ category.id }}')">
                    <img src="{% static 'icons/right-arrow.svg' %}" alt="Scroll Right" class="icon">
                </button>
            </div>
        {% endif %}
    {% endfor %}
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        bindAddToCartButtons();  // Привязываем обработчики при загрузке страницы
    });

    function bindAddToCartButtons() {
        const buttons = document.querySelectorAll('.add-to-cart-button');

        buttons.forEach(button => {
            button.removeEventListener('click', handleAddToCart);  // Удаление старого обработчика
            button.addEventListener('click', handleAddToCart, { once: true });  // Добавление нового обработчика
        });
    }

    function handleAddToCart(event) {
        const button = event.currentTarget;
        const productId = button.getAttribute('data-product-id');
        
        // Деактивация кнопки, чтобы предотвратить повторное нажатие
        button.disabled = true;

        fetch("{% url 'add_to_cart' 0 %}".replace('0', productId), {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}',
                'X-Requested-With': 'XMLHttpRequest'
            },
            body: new URLSearchParams({
                'product_id': productId
            })
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                const productDiv = document.getElementById('product-' + productId);
                button.remove();
                const message = document.createElement('p');
                message.innerText = 'Этот товар уже в корзине';
                productDiv.appendChild(message);
            }
        })
        .catch(error => {
            console.error('Ошибка:', error);
            button.disabled = false;  // Восстанавливаем кнопку в случае ошибки
        });
    }
</script>
{% endblock %}

templates/orders/edit_order_status.html
{% extends 'base.html' %}

{% block title %}Изменение статуса заказа{% endblock %}

{% block content %}
<h2>Изменение статуса заказа №{{ order.id }}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="confirm-button">Сохранить</button>
</form>

<p><a href="{% url 'manage_orders' %}">Вернуться к списку заказов</a></p>

{% endblock %}

templates/orders/edit_product.html
{% extends 'base.html' %}

{% block content %}
  <h2>Редактировать товар</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Сохранить</button>
  </form>
{% endblock %}

templates/orders/manage_orders.html
{% extends 'base.html' %}

{% block title %}Управление заказами{% endblock %}

{% block content %}
<h2>Управление заказами</h2>

<table class="order-table">
    <thead>
        <tr>
            <th>ID заказа</th>
            <th>Пользователь</th>
            <th>Дата создания</th>
            <th>Статус</th>
            <th>Общая сумма</th>
            <th>Действия</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr>
            <td>{{ order.id }}</td>
            <td>{{ order.user.username }}</td>
            <td>{{ order.created_at|date:"d.m.Y H:i" }}</td>
            <td>{{ order.get_status_display }}</td>
            <td>{{ order.total }} руб.</td>
            <td>
                <a href="{% url 'edit_order_status' order.id %}">Изменить статус</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

templates/orders/order_list.html
{% extends 'base.html' %}

{% block title %}Мои заказы{% endblock %}

{% block content %}
<h2>Мои заказы</h2>

{% if orders %}
<table class="order-table">
    <thead>
        <tr>
            <th>Номер заказа</th>
            <th>Дата</th>
            <th>Общая сумма</th>
            <th>Статус</th>
            <th>Детали</th>
        </tr>
    </thead>
    <tbody>
        {% for order in orders %}
        <tr onclick="window.location.href='{% url 'order_detail' order.id %}';" style="cursor: pointer;">
            <td>{{ order.id }}</td>
            <td>{{ order.created_at|date:"d.m.Y H:i" }}</td>
            <td>{{ order.total }} руб.</td>
            <td>{{ order.get_status_display }}</td>
            <td><a href="{% url 'order_detail' order.id %}">Посмотреть</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% else %}
<p>У вас пока нет заказов.</p>
{% endif %}

{% endblock %}

templates/orders/product_detail.html
{% extends 'base.html' %}

{% block title %}{{ product.name }}{% endblock %}

{% block content %}
<div class="product-page">
    <!-- Левая часть: изображение продукта -->
    <div class="product-image">
        <img src="{{ product.image.url }}" alt="{{ product.name }}">
    </div>

    <!-- Правая часть: описание и кнопка добавления в корзину -->
    <div class="product-info">
        <h2>{{ product.name }}</h2>
        <p>{{ product.description }}</p> <!-- Описание продукта -->
        <p class="product-price">Цена: {{ product.price }} руб.</p>
        
        <form method="post" action="{% url 'add_to_cart' product.id %}">
            {% csrf_token %}
            <button type="submit" class="add-to-cart-button">Добавить в корзину</button>
        </form>

        <!-- Кнопка для добавления или редактирования отзыва -->
        <div class="review-action">
            {% if user_review %}
                <a href="{% url 'add_review' product.id %}" class="btn btn-primary">Редактировать отзыв</a>
            {% else %}
                <a href="{% url 'add_review' product.id %}" class="btn btn-primary">Добавить отзыв</a>
            {% endif %}
        </div>
    </div>
</div>

<!-- Размещение отзывов ниже -->
<h3>Отзывы</h3>
<div class="reviews">
    {% if reviews %}
        {% for review in reviews %}
            <div class="review-item">
                <strong>{{ review.user.username }}</strong>: {{ review.comment }} ({{ review.rating }} из 5)
            </div>
        {% endfor %}
    {% else %}
        <p>Отзывов пока нет. Будьте первым, кто оставит отзыв!</p>
    {% endif %}
</div>

{% endblock %}

templates/orders/review_form.html
{% extends 'base.html' %}

{% block title %}
{% if is_editing %}
    Редактировать отзыв
{% else %}
    Добавить отзыв
{% endif %}
{% endblock %}

{% block content %}
<h2>
{% if is_editing %}
    Редактировать отзыв для {{ product.name }}
{% else %}
    Добавить отзыв для {{ product.name }}
{% endif %}
</h2>
<form method="post">
    {% csrf_token %}
    <div class="rating">
        <label for="id_rating">Рейтинг:</label>
        <div class="star-rating">
            {% for i in "54321" %}
                <input type="radio" id="star{{ i }}" name="rating" value="{{ i }}" {% if form.rating.value|stringformat:"d" == i %}checked{% endif %}/>
                <label for="star{{ i }}" title="{{ i }} звёзд">
                    <svg class="star" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#ccc" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-star">
                        <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"/>
                    </svg>
                </label>
            {% endfor %}
        </div>
    </div>
    <div class="form-group">
        <label for="id_comment">Комментарий:</label>
        {{ form.comment }}
    </div>
    <button type="submit">
    {% if is_editing %}
        Редактировать отзыв
    {% else %}
        Добавить отзыв
    {% endif %}
    </button>
</form>
{% endblock %}